### ISSUE TITLE
Can't locate object method "configure" via package "Text::ANSI::Tabs"

### ISSUE THREAD

**Issue by eserte** [kaz-utashiro/App-ansiexpand#1]
The test suite fails on some of my smoker systems:
```
#   Failed test 'option: --tabstyle=shade'
#   at t/Util.pm line 25.
Wide character in print at /usr/perl5.20.3p/lib/site_perl/5.20.3/Test2/Formatter/TAP.pm line 125.
#          got: 'Can't locate object method "configure" via package "Text::ANSI::Tabs" at /home/cpansand/.cpan/build/2021111917/App-ansiexpand-0.99-0/blib/lib/App/ansiexpand.pm line 31.
# '
#     expected: '1234▒░░░90'

#   Failed test 'option: --tabstyle=shade --tabstop=4'
#   at t/Util.pm line 25.
Wide character in print at /usr/perl5.20.3p/lib/site_perl/5.20.3/Test2/Formatter/TAP.pm line 125.
#          got: 'Can't locate object method "configure" via package "Text::ANSI::Tabs" at /home/cpansand/.cpan/build/2021111917/App-ansiexpand-0.99-0/blib/lib/App/ansiexpand.pm line 31.
# '
#     expected: '1▒░░567890'
# Looks like you failed 2 tests of 3.
t/02_expand.t .... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests 
```

This seems to happen if Text::ANSI::Tabs is too old --- with 0.06 it fails, with 0.07 it passes. Probably it's best to set a minimum version in the prerequisites.

**Comment by kaz-utashiro** [comment]
Thank you.  It's quite easy to fix, but I wonder how the situation happens.  Text::ANSI::Tabs is a recently released module, and there was only one day until upgraded to 0.07.  Are those systems intentionally use the available oldest version?

**Comment by eserte** [comment]
Not intentionally, but it may happen. Usually I run two loops on my smokers: one for recently uploaded stable versions which are in the PAUSE index, these are tested and installed. The other is for testing everything uploaded, especially non-indexed development versions, but it can also pick stable versions which are not indexed yet at PAUSE. These distributions are only tested and *not* installed. Anything which is already tested is ignored by my smokers. I suspect that this was happening here.

Another scenario: my smokers only pick the distributions uploaded in the last day up to 14 days (different configurations). If for some reason a server does not run for some hours or even days (due to server downtime, hanging smoker processes etc.) then it's possible that the newest version is never in the list of distributions to be tested and installed.

**Comment by kaz-utashiro** [comment]
Hmm... I assumed that the test is done on the clean standard distribution, but it is not, probably.  Anyway, your system is doing great job!
